
version: '3.1'
services:
  app:
    container_name: todoList-api-docker.jar
    build: ./
    ports:
    - "8080:8080"
    depends_on:
      dbpostgresql:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbpostgresql:5432/todo_db?user=postgres&password=postgres

  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  